[project]
name = "so101-tx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lerobot",
    "mujoco>=3.3.3",
]

[tool.uv.sources]
lerobot = { path = "../lerobot" }
